name: native_textfield_tv
description: "A Flutter plugin that provides native Android EditText component as a solution for Android TV remote control issues with Flutter's default TextField. According to Flutter issue #154924, the default TextField doesn't work properly with TV remotes on many Android TV devices. This plugin offers a native alternative with full TextEditingController compatibility, focus management, and real-time text access."
version: 1.0.2

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.3.0'
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.example.native_textfield_tv
        pluginClass: NativeTextfieldTvPlugin
